/*
  © 2026 Jeff Witt.

  Licensed under the MIT License. See LICENSE file at the project root or
  https://opensource.org/license/mit/ for details.

  SPDX-License-Identifier: MIT
*/

/*
  registry
  GENERATED by procs/generateRuleRegistry.js (npm run build:registry); do not edit.
  Maps each rule ID to a lazy loader of its module, preserving on-demand loading
  while giving consumers a checked RuleID union and a typed reporter (issue #73).
*/

// TYPES

// The report every rule reporter resolves with.
export interface RuleReport {
  data: unknown;
  totals: number[];
  standardInstances: unknown[];
}
// The module shape of a rule.
export interface RuleModule {
  reporter: (...args: any[]) => Promise<RuleReport>;
}

// The IDs of all rule modules.
export type RuleID =
  | 'adbID'
  | 'allCapStyle'
  | 'allCaps'
  | 'allHidden'
  | 'allSlanted'
  | 'altScheme'
  | 'attVal'
  | 'autocomplete'
  | 'bulk'
  | 'buttonMenu'
  | 'captionLoc'
  | 'datalistRef'
  | 'distortion'
  | 'docType'
  | 'dupAtt'
  | 'elements'
  | 'embAc'
  | 'focAll'
  | 'focAndOp'
  | 'focInd'
  | 'focVis'
  | 'headEl'
  | 'headingAmb'
  | 'hovInd'
  | 'hover'
  | 'hr'
  | 'imageLink'
  | 'labClash'
  | 'legendLoc'
  | 'lineHeight'
  | 'linkAmb'
  | 'linkExt'
  | 'linkOldAtt'
  | 'linkTo'
  | 'linkUl'
  | 'miniText'
  | 'motion'
  | 'nonTable'
  | 'optRoleSel'
  | 'phOnly'
  | 'pseudoP'
  | 'radioSet'
  | 'role'
  | 'secHeading'
  | 'styleDiff'
  | 'tabNav'
  | 'targetsNear'
  | 'textNodes'
  | 'textSem'
  | 'title'
  | 'titledEl'
  | 'zIndex';

// CONSTANTS

// Lazy loaders of the rule modules, keyed by rule ID.
export const ruleModules = {
  adbID: () => require('./adbID') as typeof import('./adbID'),
  allCapStyle: () => require('./allCapStyle') as typeof import('./allCapStyle'),
  allCaps: () => require('./allCaps') as typeof import('./allCaps'),
  allHidden: () => require('./allHidden') as typeof import('./allHidden'),
  allSlanted: () => require('./allSlanted') as typeof import('./allSlanted'),
  altScheme: () => require('./altScheme') as typeof import('./altScheme'),
  attVal: () => require('./attVal') as typeof import('./attVal'),
  autocomplete: () => require('./autocomplete') as typeof import('./autocomplete'),
  bulk: () => require('./bulk') as typeof import('./bulk'),
  buttonMenu: () => require('./buttonMenu') as typeof import('./buttonMenu'),
  captionLoc: () => require('./captionLoc') as typeof import('./captionLoc'),
  datalistRef: () => require('./datalistRef') as typeof import('./datalistRef'),
  distortion: () => require('./distortion') as typeof import('./distortion'),
  docType: () => require('./docType') as typeof import('./docType'),
  dupAtt: () => require('./dupAtt') as typeof import('./dupAtt'),
  elements: () => require('./elements') as typeof import('./elements'),
  embAc: () => require('./embAc') as typeof import('./embAc'),
  focAll: () => require('./focAll') as typeof import('./focAll'),
  focAndOp: () => require('./focAndOp') as typeof import('./focAndOp'),
  focInd: () => require('./focInd') as typeof import('./focInd'),
  focVis: () => require('./focVis') as typeof import('./focVis'),
  headEl: () => require('./headEl') as typeof import('./headEl'),
  headingAmb: () => require('./headingAmb') as typeof import('./headingAmb'),
  hovInd: () => require('./hovInd') as typeof import('./hovInd'),
  hover: () => require('./hover') as typeof import('./hover'),
  hr: () => require('./hr') as typeof import('./hr'),
  imageLink: () => require('./imageLink') as typeof import('./imageLink'),
  labClash: () => require('./labClash') as typeof import('./labClash'),
  legendLoc: () => require('./legendLoc') as typeof import('./legendLoc'),
  lineHeight: () => require('./lineHeight') as typeof import('./lineHeight'),
  linkAmb: () => require('./linkAmb') as typeof import('./linkAmb'),
  linkExt: () => require('./linkExt') as typeof import('./linkExt'),
  linkOldAtt: () => require('./linkOldAtt') as typeof import('./linkOldAtt'),
  linkTo: () => require('./linkTo') as typeof import('./linkTo'),
  linkUl: () => require('./linkUl') as typeof import('./linkUl'),
  miniText: () => require('./miniText') as typeof import('./miniText'),
  motion: () => require('./motion') as typeof import('./motion'),
  nonTable: () => require('./nonTable') as typeof import('./nonTable'),
  optRoleSel: () => require('./optRoleSel') as typeof import('./optRoleSel'),
  phOnly: () => require('./phOnly') as typeof import('./phOnly'),
  pseudoP: () => require('./pseudoP') as typeof import('./pseudoP'),
  radioSet: () => require('./radioSet') as typeof import('./radioSet'),
  role: () => require('./role') as typeof import('./role'),
  secHeading: () => require('./secHeading') as typeof import('./secHeading'),
  styleDiff: () => require('./styleDiff') as typeof import('./styleDiff'),
  tabNav: () => require('./tabNav') as typeof import('./tabNav'),
  targetsNear: () => require('./targetsNear') as typeof import('./targetsNear'),
  textNodes: () => require('./textNodes') as typeof import('./textNodes'),
  textSem: () => require('./textSem') as typeof import('./textSem'),
  title: () => require('./title') as typeof import('./title'),
  titledEl: () => require('./titledEl') as typeof import('./titledEl'),
  zIndex: () => require('./zIndex') as typeof import('./zIndex'),
} satisfies Record<RuleID, () => RuleModule>;
