/*
  © 2026 Jeff Witt.

  Licensed under the MIT License. See LICENSE file at the project root or
  https://opensource.org/license/mit/ for details.

  SPDX-License-Identifier: MIT
*/

/*
  generateRuleRegistry
  Build tool: writes testaro/registry.ts from the rule modules present in the
  testaro directory (issue #73). Run with npm run build:registry; the CI
  workflow regenerates the registry and fails on drift, so the committed
  registry always matches the rule modules on disk.
*/

// IMPORTS

const fs = require('fs');
const path = require('path');

// CONSTANTS

const ruleDir = path.join(__dirname, '..', 'testaro');
const registryPath = path.join(ruleDir, 'registry.ts');

// OPERATION

// Get the rule IDs: every TypeScript rule module in the directory.
const ruleIDs = fs.readdirSync(ruleDir)
.filter(name => name.endsWith('.ts') && ! name.endsWith('.d.ts'))
.map(name => name.replace(/\.ts$/, ''))
.filter(name => name !== 'registry')
.sort();
// Compose the registry source.
const lines = [];
lines.push(
  '/*',
  '  © 2026 Jeff Witt.',
  '',
  '  Licensed under the MIT License. See LICENSE file at the project root or',
  '  https://opensource.org/license/mit/ for details.',
  '',
  '  SPDX-License-Identifier: MIT',
  '*/',
  '',
  '/*',
  '  registry',
  '  GENERATED by procs/generateRuleRegistry.js (npm run build:registry); do not edit.',
  '  Maps each rule ID to a lazy loader of its module, preserving on-demand loading',
  '  while giving consumers a checked RuleID union and a typed reporter (issue #73).',
  '*/',
  '',
  '// TYPES',
  '',
  '// The report every rule reporter resolves with.',
  'export interface RuleReport {',
  '  data: unknown;',
  '  totals: number[];',
  '  standardInstances: unknown[];',
  '}',
  '// The module shape of a rule.',
  'export interface RuleModule {',
  '  reporter: (...args: any[]) => Promise<RuleReport>;',
  '}',
  '',
  '// The IDs of all rule modules.',
  'export type RuleID =');
ruleIDs.forEach((id, index) => {
  lines.push(`  | '${id}'${index === ruleIDs.length - 1 ? ';' : ''}`);
});
lines.push(
  '',
  '// CONSTANTS',
  '',
  '// Lazy loaders of the rule modules, keyed by rule ID.',
  'export const ruleModules = {');
ruleIDs.forEach(id => {
  lines.push(`  ${id}: () => require('./${id}') as typeof import('./${id}'),`);
});
lines.push(
  '} satisfies Record<RuleID, () => RuleModule>;',
  '');
// Write the registry if it changed.
const source = lines.join('\n');
const existing = fs.existsSync(registryPath) ? fs.readFileSync(registryPath, 'utf8') : '';
if (source !== existing) {
  fs.writeFileSync(registryPath, source);
  console.log(`Wrote ${registryPath} with ${ruleIDs.length} rules`);
}
else {
  console.log(`Registry is current (${ruleIDs.length} rules)`);
}
